spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/qltc
      username: root
      password: 4436
      max-active: 20
      max-wait: 5000
      initial-size: 2

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.qlttcn.nhom2.model
  global-config:
    db-config:
      id-type: auto
    banner: false

server:
  port: 8090